[package]
name = "lg"
version = "0.1.0"
authors = ["lemma"]
edition = "2018"

[dependencies]
unicode-segmentation = "1.3.0"
chrono = {version = "0.4", features = ["serde"]}
serde_yaml = "0.8"
serde = {version = "1.0", features = ["derive"]}